from __future__ import annotations

import logging
import uuid
from pathlib import Path
from typing import Any

from agents.image.backends import HFInferenceBackend, ImageBackend, PollinationsBackend
from agents.image.models import ImageArtifact
from api.settings import settings
from workers.jobs import BaseWorkerJob

logger = logging.getLogger(__name__)


async def _save_artifact_local(
    image_bytes: bytes, prompt: str, width: int, height: int
) -> ImageArtifact:
    """Save image to local filesystem. T16 will replace with S3/MinIO."""
    artifact_id = str(uuid.uuid4())
    artifacts_dir = Path(settings.artifacts_local_path)
    artifacts_dir.mkdir(parents=True, exist_ok=True)
    image_path = artifacts_dir / f"{artifact_id}.jpg"
    image_path.write_bytes(image_bytes)
    return ImageArtifact(
        artifact_id=artifact_id,
        url=f"/artifacts/{artifact_id}",
        width=width,
        height=height,
        prompt=prompt,
    )


class ImageGenerationJob(BaseWorkerJob):
    """arq job: generate an image with Pollinations → HF Inference fallback."""

    def __init__(
        self,
        job_id: str,
        ctx: dict[str, Any],
        prompt: str,
        width: int = 1280,
        height: int = 720,
        backends: list[ImageBackend] | None = None,
    ) -> None:
        super().__init__(job_id, ctx)
        self.prompt = prompt
        self.width = width
        self.height = height
        self._backends: list[ImageBackend] = backends or [
            PollinationsBackend(),
            HFInferenceBackend(
                token=settings.hf_token,
                timeout=float(settings.hf_inference_timeout),
            ),
        ]

    async def run(self) -> dict[str, Any]:
        await self.on_progress(10, "Starting image generation...")

        image_bytes: bytes | None = None
        for backend in self._backends:
            name = type(backend).__name__
            try:
                await self.on_progress(30, f"Generating with {name}...")
                image_bytes = await backend.generate(self.prompt, self.width, self.height)
                logger.info("Image generated by %s", name)
                break
            except Exception as exc:
                logger.warning("%s failed: %s — trying next backend", name, exc)

        if image_bytes is None:
            raise RuntimeError("All image generation backends failed")

        await self.on_progress(80, "Saving artifact...")
        artifact = await _save_artifact_local(image_bytes, self.prompt, self.width, self.height)

        await self.on_progress(100, "Done")
        return artifact.to_dict()


# ---------------------------------------------------------------------------
# arq job function
# ---------------------------------------------------------------------------


async def run_image_job(
    ctx: dict[str, Any],
    job_id: str,
    prompt: str,
    width: int = 1280,
    height: int = 720,
) -> dict[str, Any]:
    """arq entry point — runs ImageGenerationJob."""
    return await ImageGenerationJob(
        job_id=job_id, ctx=ctx, prompt=prompt, width=width, height=height
    ).run()
